---
- hosts: dynamic_host
  remote_user: root
  vars:
    touch_file: zhangneng.txt
  tasks:
    - name: touch file
      shell: "touch /tmp/{{touch_file}}"
    - name: get date
      command: date
      register: date_output
    - name: get date
      shell: "echo {{date_output.stdout}}>/tmp/{{touch_file}}"